# this yaml file will contain required fields and constraints

validation_rules:
  required_fields:
    - Transaction ID
    - Customer ID
    - Category
    - Item
    - Price Per Unit
    - Quantity
    - Total Spent
    - Payment Method
    - Location
    - Transaction Date
  
  field_types:
    Transaction ID: str
    Customer ID: str
    Category: str
    Item: str
    Price Per Unit: float
    Quantity: int
    Total Spent: float
    Payment Method: str
    Location: str
    Transaction Date: date
    Discount Applied: bool

  constraints:
    Quantity:
      min: 1
    Price Per Unit:
      min: 0
    Total Spent:
      min: 0
    Transaction ID:
      like: '[0-9]+$'
    Customer ID:
      like: '[0-9]+$'
    Item:
      like: '[0-9]+_[a-zA-Z]+$'
    Payment Method:
      in: 
        - digital wallet 
        - credit card 
        - cash
    Location:
      in: 
        - online
        - in-store
  
  optional_defaults:
    Discount Applied: False

string_cleaning_formats:
  title case: 
    columns:
      - Payment Method
      - Location
      - Category
  id_format: 
    regex: '([0-9]+$)'
    columns: 
      - Transaction ID
      - Customer ID
  item_format: 
    regex: '([0-9]+_[a-zA-Z]+$)'
    columns: 
      - Item




